### ISSUE TITLE
TGRelay doesn't detect messages

### ISSUE THREAD

**Issue by jcjordyn130** [WildPHP/module-tgrelay#2]
It seems to be that the message recieveing loop is never running, I'm sure I have the right chatID in there.

**Comment by Yoshi2889** [comment]
That is odd, you're sure the module starts properly? Also if you're running multiple instances only 1 of them will catch messages, this due to the way the Telegram API works. Finally, make sure you're running the latest dev version of the bot (master branch).

**Comment by jcjordyn130** [comment]
Closing, and for anyone who wants to know it was user error.
